# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create a non-root user
RUN addgroup -g 1001 -S mcpuser && \
    adduser -S mcpuser -u 1001 -G mcpuser

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts && \
    npm audit fix && \
    npm cache clean --force

# Copy the remainder of the application
COPY . .

# Build the application
RUN npm run build

# Change ownership to non-root user
RUN chown -R mcpuser:mcpuser /app

# Switch to non-root user
USER mcpuser

# Do not expose ports for security (runs on stdio)
# EXPOSE 3000

CMD [ "node", "dist/index.js" ]
